server:
  port: 5050

spring:
  datasource:
    druid:
    name: test
    url: jdbc:mysql://39.105.123.124:3306/springBoot?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: zzy
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  devtools:
    restart:
      enabled: true
      additional-paths: resources/**,static/**,templates/**
      exclude: data/**
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
mybatis:
  mapper-locations: classpath:com/springboot/demo/mapper/xml/*.xml
  type-aliases-package: springboot.test.model

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

logging.level.com.springboot.demo.mapper: debug